"""create initial tables

Revision ID: 62d4c3bf8115
Revises: 
Create Date: 2026-10-02 20:28:11.657037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62d4c3bf8115'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('business_phone', sa.String(length=30), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Karachi', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('messaging_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer_groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_groups_organization_id'), 'customer_groups', ['organization_id'], unique=False)
    op.create_table('customers',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.Enum('buyer', 'tenant', 'seller', 'landlord', 'investor', 'general_inquiry', name='customertype', native_enum=False, length=32), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_type'), 'customers', ['customer_type'], unique=False)
    op.create_index('ix_customers_org_city', 'customers', ['organization_id', 'city'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_index('uq_customers_org_email', 'customers', ['organization_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_customers_org_phone', 'customers', ['organization_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('integrations',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_mock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), server_default='30', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'kind', 'provider', name='uq_integration')
    )
    op.create_index(op.f('ix_integrations_organization_id'), 'integrations', ['organization_id'], unique=False)
    op.create_table('message_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.Enum('english', 'urdu', 'roman_urdu', name='messagelanguage', native_enum=False, length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('whatsapp_template_name', sa.String(length=200), nullable=True),
    sa.Column('approval_status', sa.Enum('not_applicable', 'draft', 'pending', 'approved', 'rejected', name='templateapprovalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_organization_id'), 'message_templates', ['organization_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_run_at', 'scheduled_jobs', ['status', 'run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_organization_id'), 'scheduled_jobs', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_organization_id'), 'webhook_events', ['organization_id'], unique=False)
    op.create_index('ix_webhook_provider_processed', 'webhook_events', ['provider', 'processed'], unique=False)
    op.create_table('ai_generations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('tone', sa.String(length=30), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('prompt_summary', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_organization_id'), 'ai_generations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_generations_user_id'), 'ai_generations', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.Enum('new_property_alert', 'price_reduction', 'open_house_invitation', 'viewing_reminder', 'customer_follow_up', 'rental_availability_alert', 'sold_or_rented_announcement', 'seasonal_campaign', 'investor_opportunity', 'custom', name='campaigntype', native_enum=False, length=32), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'processing', 'running', 'completed', 'paused', 'cancelled', 'failed', name='campaignstatus', native_enum=False, length=32), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('english', 'urdu', 'roman_urdu', name='messagelanguage', native_enum=False, length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('is_personalized', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('audience_filter', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('follow_up_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Karachi', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_org_status', 'campaigns', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_table('customer_consents',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('granted', 'revoked', name='consentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consents_customer_channel', 'customer_consents', ['customer_id', 'channel', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_customer_consents_customer_id'), 'customer_consents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_consents_organization_id'), 'customer_consents', ['organization_id'], unique=False)
    op.create_table('customer_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['customer_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'customer_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_customer_group_members_customer_id'), 'customer_group_members', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_group_members_group_id'), 'customer_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_customer_group_members_organization_id'), 'customer_group_members', ['organization_id'], unique=False)
    op.create_table('customer_requirements',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_categories', sa.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('preferred_locations', sa.ARRAY(sa.String(length=150)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('purpose', sa.Enum('sale', 'rent', 'lease', name='propertypurpose', native_enum=False, length=32), nullable=True),
    sa.Column('use_preference', sa.Enum('residential', 'commercial', name='propertyuse', native_enum=False, length=32), nullable=True),
    sa.Column('min_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('area_unit', sa.String(length=20), server_default='sqft', nullable=False),
    sa.Column('min_bedrooms', sa.Integer(), nullable=True),
    sa.Column('min_bathrooms', sa.Integer(), nullable=True),
    sa.Column('furnishing_preference', sa.Enum('furnished', 'semi_furnished', 'unfurnished', name='furnishingstatus', native_enum=False, length=32), nullable=True),
    sa.Column('required_amenities', sa.ARRAY(sa.String(length=100)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_area IS NULL OR min_area IS NULL OR max_area >= min_area', name='ck_requirements_area_range'),
    sa.CheckConstraint('max_budget IS NULL OR min_budget IS NULL OR max_budget >= min_budget', name='ck_requirements_budget_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_requirements_customer_id'), 'customer_requirements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_requirements_organization_id'), 'customer_requirements', ['organization_id'], unique=False)
    op.create_table('customer_tags',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'tag', name='uq_customer_tag')
    )
    op.create_index(op.f('ix_customer_tags_customer_id'), 'customer_tags', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_tags_organization_id'), 'customer_tags', ['organization_id'], unique=False)
    op.create_table('leads',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'property_shared', 'visit_scheduled', 'negotiation', 'converted', 'lost', 'unresponsive', name='leadstatus', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_agent_id'), 'leads', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_index('ix_leads_org_followup', 'leads', ['organization_id', 'next_follow_up_at'], unique=False)
    op.create_index('ix_leads_org_status', 'leads', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_table('properties',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('house', 'apartment', 'plot', 'shop', 'office', 'warehouse', 'farmhouse', 'commercial_building', 'other', name='propertycategory', native_enum=False, length=32), nullable=False),
    sa.Column('purpose', sa.Enum('sale', 'rent', 'lease', name='propertypurpose', native_enum=False, length=32), nullable=False),
    sa.Column('use_type', sa.Enum('residential', 'commercial', name='propertyuse', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'available', 'reserved', 'sold', 'rented', 'inactive', 'archived', name='propertystatus', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='PKR', nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('covered_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('plot_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('area_unit', sa.String(length=20), server_default='sqft', nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('furnishing', sa.Enum('furnished', 'semi_furnished', 'unfurnished', name='furnishingstatus', native_enum=False, length=32), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), server_default='0', nullable=False),
    sa.Column('nearby_landmarks', sa.ARRAY(sa.String(length=150)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('virtual_tour_url', sa.String(length=500), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=30), nullable=True),
    sa.Column('owner_notes', sa.Text(), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_properties_price_nonneg'),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    op.create_index(op.f('ix_properties_assigned_agent_id'), 'properties', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_properties_category'), 'properties', ['category'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index('ix_properties_org_status', 'properties', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_properties_organization_id'), 'properties', ['organization_id'], unique=False)
    op.create_index(op.f('ix_properties_purpose'), 'properties', ['purpose'], unique=False)
    op.create_index('ix_properties_search', 'properties', ['organization_id', 'city', 'purpose', 'category'], unique=False)
    op.create_index('uq_properties_org_reference', 'properties', ['organization_id', 'reference'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('suppression_lists',
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Enum('unsubscribed', 'bounced', 'complaint', 'invalid', 'manual', name='suppressionreason', native_enum=False, length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'channel', 'address', name='uq_suppression_entry')
    )
    op.create_index(op.f('ix_suppression_lists_customer_id'), 'suppression_lists', ['customer_id'], unique=False)
    op.create_index(op.f('ix_suppression_lists_organization_id'), 'suppression_lists', ['organization_id'], unique=False)
    op.create_table('appointments',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('status', sa.Enum('requested', 'scheduled', 'confirmed', 'rescheduled', 'completed', 'cancelled', 'no_show', name='appointmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('interest_level', sa.Enum('low', 'medium', 'high', name='interestlevel', native_enum=False, length=32), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_agent_id'), 'appointments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index('ix_appointments_org_time', 'appointments', ['organization_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_property_id'), 'appointments', ['property_id'], unique=False)
    op.create_table('campaign_properties',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'property_id', name='uq_campaign_property')
    )
    op.create_index(op.f('ix_campaign_properties_campaign_id'), 'campaign_properties', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_properties_organization_id'), 'campaign_properties', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_properties_property_id'), 'campaign_properties', ['property_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'excluded', 'queued', 'sent', 'failed', name='recipientstatus', native_enum=False, length=32), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'customer_id', name='uq_campaign_customer'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_customer_id'), 'campaign_recipients', ['customer_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_organization_id'), 'campaign_recipients', ['organization_id'], unique=False)
    op.create_table('lead_assignments',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assignments_lead_id'), 'lead_assignments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_organization_id'), 'lead_assignments', ['organization_id'], unique=False)
    op.create_table('lead_notes',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_notes_lead_id'), 'lead_notes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_organization_id'), 'lead_notes', ['organization_id'], unique=False)
    op.create_table('property_amenities',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'name', name='uq_property_amenity')
    )
    op.create_index(op.f('ix_property_amenities_organization_id'), 'property_amenities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_amenities_property_id'), 'property_amenities', ['property_id'], unique=False)
    op.create_table('property_documents',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_documents_organization_id'), 'property_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_documents_property_id'), 'property_documents', ['property_id'], unique=False)
    op.create_table('property_images',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_organization_id'), 'property_images', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_table('property_matches',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'approved', 'rejected', name='matchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_match_score_range'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'property_id', name='uq_match_customer_property')
    )
    op.create_index(op.f('ix_property_matches_customer_id'), 'property_matches', ['customer_id'], unique=False)
    op.create_index(op.f('ix_property_matches_organization_id'), 'property_matches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_matches_property_id'), 'property_matches', ['property_id'], unique=False)
    op.create_table('property_tags',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'tag', name='uq_property_tag')
    )
    op.create_index(op.f('ix_property_tags_organization_id'), 'property_tags', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_tags_property_id'), 'property_tags', ['property_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'cancelled', name='followupstatus', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_assigned_to_id'), 'follow_ups', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_customer_id'), 'follow_ups', ['customer_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_organization_id'), 'follow_ups', ['organization_id'], unique=False)
    op.create_index('ix_followups_org_due', 'follow_ups', ['organization_id', 'status', 'due_at'], unique=False)
    op.create_table('messages',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), server_default='outbound', nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'accepted', 'sent', 'delivered', 'read', 'failed', 'unknown', name='messagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('is_mock', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['campaign_recipients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_messages_campaign_id'), 'messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_messages_customer_id'), 'messages', ['customer_id'], unique=False)
    op.create_index('ix_messages_org_status', 'messages', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_messages_provider_message_id'), 'messages', ['provider_message_id'], unique=False)
    op.create_table('message_events',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('provider_status', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_events_message_id'), 'message_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_events_organization_id'), 'message_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_events_organization_id'), table_name='message_events')
    op.drop_index(op.f('ix_message_events_message_id'), table_name='message_events')
    op.drop_table('message_events')
    op.drop_index(op.f('ix_messages_provider_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index('ix_messages_org_status', table_name='messages')
    op.drop_index(op.f('ix_messages_customer_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_campaign_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_followups_org_due', table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_organization_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_customer_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_assigned_to_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_property_tags_property_id'), table_name='property_tags')
    op.drop_index(op.f('ix_property_tags_organization_id'), table_name='property_tags')
    op.drop_table('property_tags')
    op.drop_index(op.f('ix_property_matches_property_id'), table_name='property_matches')
    op.drop_index(op.f('ix_property_matches_organization_id'), table_name='property_matches')
    op.drop_index(op.f('ix_property_matches_customer_id'), table_name='property_matches')
    op.drop_table('property_matches')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_organization_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_property_documents_property_id'), table_name='property_documents')
    op.drop_index(op.f('ix_property_documents_organization_id'), table_name='property_documents')
    op.drop_table('property_documents')
    op.drop_index(op.f('ix_property_amenities_property_id'), table_name='property_amenities')
    op.drop_index(op.f('ix_property_amenities_organization_id'), table_name='property_amenities')
    op.drop_table('property_amenities')
    op.drop_index(op.f('ix_lead_notes_organization_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_lead_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index(op.f('ix_lead_assignments_organization_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_lead_id'), table_name='lead_assignments')
    op.drop_table('lead_assignments')
    op.drop_index(op.f('ix_campaign_recipients_organization_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_customer_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_campaign_properties_property_id'), table_name='campaign_properties')
    op.drop_index(op.f('ix_campaign_properties_organization_id'), table_name='campaign_properties')
    op.drop_index(op.f('ix_campaign_properties_campaign_id'), table_name='campaign_properties')
    op.drop_table('campaign_properties')
    op.drop_index(op.f('ix_appointments_property_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index('ix_appointments_org_time', table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_agent_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_suppression_lists_organization_id'), table_name='suppression_lists')
    op.drop_index(op.f('ix_suppression_lists_customer_id'), table_name='suppression_lists')
    op.drop_table('suppression_lists')
    op.drop_index('uq_properties_org_reference', table_name='properties', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_properties_search', table_name='properties')
    op.drop_index(op.f('ix_properties_purpose'), table_name='properties')
    op.drop_index(op.f('ix_properties_organization_id'), table_name='properties')
    op.drop_index('ix_properties_org_status', table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_category'), table_name='properties')
    op.drop_index(op.f('ix_properties_assigned_agent_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index('ix_leads_org_status', table_name='leads')
    op.drop_index('ix_leads_org_followup', table_name='leads')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_agent_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_customer_tags_organization_id'), table_name='customer_tags')
    op.drop_index(op.f('ix_customer_tags_customer_id'), table_name='customer_tags')
    op.drop_table('customer_tags')
    op.drop_index(op.f('ix_customer_requirements_organization_id'), table_name='customer_requirements')
    op.drop_index(op.f('ix_customer_requirements_customer_id'), table_name='customer_requirements')
    op.drop_table('customer_requirements')
    op.drop_index(op.f('ix_customer_group_members_organization_id'), table_name='customer_group_members')
    op.drop_index(op.f('ix_customer_group_members_group_id'), table_name='customer_group_members')
    op.drop_index(op.f('ix_customer_group_members_customer_id'), table_name='customer_group_members')
    op.drop_table('customer_group_members')
    op.drop_index(op.f('ix_customer_consents_organization_id'), table_name='customer_consents')
    op.drop_index(op.f('ix_customer_consents_customer_id'), table_name='customer_consents')
    op.drop_index('ix_consents_customer_channel', table_name='customer_consents')
    op.drop_table('customer_consents')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index('ix_campaigns_org_status', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_audit_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_generations_user_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_organization_id'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index('ix_webhook_provider_processed', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_organization_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduled_jobs_organization_id'), table_name='scheduled_jobs')
    op.drop_index('ix_jobs_status_run_at', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_message_templates_organization_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_integrations_organization_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('uq_customers_org_phone', table_name='customers', postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_customers_org_email', table_name='customers', postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index('ix_customers_org_city', table_name='customers')
    op.drop_index(op.f('ix_customers_customer_type'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customer_groups_organization_id'), table_name='customer_groups')
    op.drop_table('customer_groups')
    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
